### 前提条件変更
POST http://localhost:8080/api/cart
Content-Type: application/json

{
    "productId": 1,
    "quantity": 1
}
### No. 3-17-1 注文（異常系 - 顧客情報不足、名前が空）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "",
"email": "test-member-a@example.com",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card",
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 1,
"subtotal": 3500
}
],
"totalPrice": 3500,
"shippingFee": 500,
"grandTotal": 4000
}

### No. 3-17-2 注文（異常系 - 顧客情報不足、メールアドレスが空）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客　太郎",
"email": "",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card",
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 1,
"subtotal": 3500
}
],
"totalPrice": 3500,
"shippingFee": 500,
"grandTotal": 4000
}
### No. 3-17-3 注文（異常系 - 顧客情報不足、住所が空）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客　太郎",
"email": "test-member-a@example.com",
"address": "",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card",
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 1,
"subtotal": 3500
}
],
"totalPrice": 3500,
"shippingFee": 500,
"grandTotal": 4000
}
### No. 3-17-4 注文（異常系 - 顧客情報不足、電話番号が空）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客　太郎",
"email": "test-member-a@example.com",
"address": "東京都品川区",
"phoneNumber": ""
},
"paymentMethod": "credit_card",
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 1,
"subtotal": 3500
}
],
"totalPrice": 3500,
"shippingFee": 500,
"grandTotal": 4000
}
### No. 3-17-5 注文（異常系 - 顧客情報不足、支払い方法が空）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客　太郎",
"email": "test-member-a@example.com",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "",
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 1,
"subtotal": 3500
}
],
"totalPrice": 3500,
"shippingFee": 500,
"grandTotal": 4000
}