### No. 3-14_注文（異常系 - カートが空の状態で注文）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客 太郎",
"email": "test-member-a@example.com",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card",
"items": [

],
"totalPrice": 0,
"shippingFee": 0,
"grandTotal": 0
}


### No. 3-15_注文（異常系 - 注文処理中に在庫不足が発生）
### 前提条件
POST http://localhost:8080/api/cart
Content-Type: application/json

{
    "productId": 1,
    "quantity": 3
}
- データベースでproductId:1 の商品を2個にする

### 入力
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客 太郎",
"email": "test-member-a@example.com",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card",
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 3,
"subtotal": 10500
}
],
"totalPrice": 10500,
"shippingFee": 0,
"grandTotal": 10500
}
↓データベース変更
### 3.16 前提条件
POST http://localhost:8080/api/cart
Content-Type: application/json

{
    "productId": 999,
    "quantity": 1
}

↓データベース変更
### No. 3-16_注文（異常系 - カート内の商品がDBに存在しない）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客 太郎",
"email": "test-member-a@example.com",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card",
"items": [
{
"productId": 999,
"name": "不明な商品",
"price": 1000,
"quantity": 1,
"subtotal": 1000
}
],
"totalPrice": 1000,
"shippingFee": 500,
"grandTotal": 1000
}

### No. 3-17_注文（異常系 - 顧客情報不足、例：名前が空）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "",
"email": "test-member-a@example.com",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card",
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 1,
"subtotal": 3500
}
],
"totalPrice": 3500,
"shippingFee": 500,
"grandTotal": 4000
}

### No. 3-18_注文（異常系 - 顧客情報の形式が不正、例：メール形式不正）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客 太郎",
"email": "invalid-email",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card", 
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 1,
"subtotal": 3500
}
],
"totalPrice": 3500,
"shippingFee": 500,
"grandTotal": 4000
}

### No. 3-19_1 注文（異常系 - リクエストボディが空）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

### No. 3-19_2 注文（異常系 - JSON形式として文法的に不正：値が欠落）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": ,
"paymentMethod": "credit_card", 
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 1,
"subtotal": 3500
}
],
"totalPrice": 3500,
"shippingFee": 500,
"grandTotal": 4000
}

### No. 3-19_3 注文（異常系 - JSON形式として文法的に不正：構文エラー）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客 太郎",
"email": "invalid-email",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card", 
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 1,
"subtotal": 3500
}
],
"totalPrice": 3500,
"shippingFee": 500,
"grandTotal": 4000
}



### No. 3-20 前提条件
POST http://localhost:8080/api/cart
Content-Type: application/json

{
    "productId": 1,
    "quantity": 1
}
↓ordersviceを変更（throw new RuntimeExceptionをコメントからコードに、saveorderメソッドをコメントアウト）
### No. 3-20_注文（異常系 - (模擬) 注文DB保存時にエラー発生）
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客 太郎",
"email": "test-member-a@example.com",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card",
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 1,
"subtotal": 3500
}
],
"totalPrice": 3500,
"shippingFee": 500,
"grandTotal": 4000
}

### No. 3-21_注文（異常系 - (模擬) 在庫更新時にエラー発生）
### 前提条件
POST http://localhost:8080/api/cart
Content-Type: application/json

{
    "productId": 1,
    "quantity": 3
}
↓「private boolean simulateStockUpdateFailure 」や「if (simulateStockUpdateFailure)~」を有効化

### 入力
POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客 太郎",
"email": "test-member-a@example.com",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card",
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 3,
"subtotal": 10500
}
],
"totalPrice": 10500,
"shippingFee": 0,
"grandTotal": 10500
}

### No. 3-22_注文（異常系 - (模擬) カートクリア時にエラー発生）

POST http://localhost:8080/api/order/confirm
Content-Type: application/json

{
"customerInfo": {
"name": "顧客 太郎",
"email": "test-member-a@example.com",
"address": "東京都品川区",
"phoneNumber": "0123456789"
},
"paymentMethod": "credit_card",
"items": [
{
"productId": 1,
"name": "シンプルデスクオーガナイザー",
"price": 3500,
"quantity": 1,
"subtotal": 3500
}
],
"totalPrice": 3500,
"shippingFee": 500,
"grandTotal": 4000
}

